### ISSUE TITLE
U and V grid support

### ISSUE THREAD

**Issue by andrewgryan** [met-office-ocean/obsoper#7]
### U and V grid support

The horizontal interpolation algorithm fails to interpolate correctly on the U/V grid. Requirement to add support for U and V ORCA025 horizontal grids.

**Comment by andrewgryan** [comment]
@isabellaascione this issue should work towards fixing the interpolator algorithm failures you've been having

**Comment by andrewgryan** [comment]
Included stack traceback to make finding issue easier.
```
Processing 2015-01-10 00:00:00
Reading grid positions: model/prodm_op_gl.gridU_20150110_00.012.nc
Reading observed positions: obs/driftertrajGPS_1.01_U_out.nc
Mapping positions to grid: 2015-01-10 00:00:00
Traceback (most recent call last):
  File "/home/h03/frrn/share/usr/local/sci/bin/c4ice", line 11, in <module>
    sys.exit(main())
  File "/home/h03/frrn/share/usr/local/sci/lib/python2.7/site-packages/c4tools/ice/main.py", line 165, in main
    args.parameters))
  File "/home/h03/frrn/share/usr/local/sci/lib/python2.7/site-packages/c4tools/ice/main.py", line 218, in process_date
    obs_latitudes)
  File "/home/h03/frrn/share/usr/local/sci/lib/python2.7/site-packages/c4tools/ice/interp.py", line 59, in tripolar_halo
    has_halo=True)
  File "/home/h03/frrn/share/usr/local/sci/lib/python2.7/site-packages/obsoper/core.py", line 58, in __init__
    has_halo=has_halo)
  File "/home/h03/frrn/share/usr/local/sci/lib/python2.7/site-packages/obsoper/horizontal.py", line 185, in __init__
    boundary="band")
  File "/home/h03/frrn/share/usr/local/sci/lib/python2.7/site-packages/obsoper/horizontal.py", line 79, in __init__
    search=search)
  File "/home/h03/frrn/share/usr/local/sci/lib/python2.7/site-packages/obsoper/grid.py", line 42, in lower_left
    observed_latitudes)
  File "/home/h03/frrn/share/usr/local/sci/lib/python2.7/site-packages/obsoper/grid.py", line 79, in lower_left
    ri, rj = self.walk.query(longitudes, latitudes, i, j)
  File "obsoper/walk.pyx", line 59, in obsoper.walk.Walk.query (obsoper/walk.c:2632)
  File "obsoper/walk.pyx", line 78, in obsoper.walk.Walk._query (obsoper/walk.c:2874)
  File "obsoper/walk.pyx", line 94, in obsoper.walk.Walk._query_one (obsoper/walk.c:3483)
  File "obsoper/walk.pyx", line 114, in obsoper.walk.Walk.detect (obsoper/walk.c:3919)
  File "obsoper/walk.pyx", line 136, in obsoper.walk.Walk.brute_force (obsoper/walk.c:4539)
```
